### ISSUE TITLE
[question] 처리율 제한 장치와 로드밸런서

### ISSUE THREAD

**Issue by hyunrrr** [caffeine-library/system-design-interview#14]
## 질문
처리율 제한 장치와 로드밸런서의 관계가 어떻게 되는지 궁금합니다.
 
처음에는 
1. 처리율 제한 장치에서 처리할 요청을 거름 
2. 처리할 요청을 로드밸런서로 분배함

이렇게 생각했었는데 로드밸런서 앞에 처리율 제한 장치를  구현한다면 로드밸런서의 의미가 없어지는게 아닌가(왜냐면 처리율 제한 장치로 트래픽이 다 몰리니까, 그림 4-16 처럼 중앙 집중형 데이터 저장소를 쓴다면 특히)란 생각이 들었습니다.

그래서 저는 그림 1-15에 처리율 제한 장치를 추가한다면 로드밸런서 앞에 추가해야 하는지, 각 데이터센터 내부에 추가해야 하는지가 궁금합니다.
## 연관 챕터

#1 
#10 

@caffeine-library/readers-system-design-interview

**Comment by JasonYoo1995** [comment]
<img width=600 src=https://user-images.githubusercontent.com/66045861/148672542-c53a5dfe-0633-43c1-8c26-ecfb6bcc372f.png>
<img width=600 src=https://user-images.githubusercontent.com/66045861/148672572-8ad676f3-8a64-43de-bb73-f06e17131eba.png>

- 트래픽이 많아서 로드밸런서에 Bottleneck이 생긴다면, 로드밸런서를 Scale Out 할 수 있습니다.
- API Gateway 같은 경우, 로드밸런싱과 처리율 제한 2가지 기능을 동시에 제공합니다.
- 처리율 제한은 다양한 단위로 적용 가능합니다.
