### ISSUE TITLE
[keyword] 1장 - 사용자 수에 따른 규모 확장성

### ISSUE THREAD

**Issue by JasonYoo1995** [caffeine-library/system-design-interview#2]
## 주제

'1장 - 사용자 수에 따른 규모 확장성'을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터

#1 

@caffeine-library/readers-system-design-interview

**Comment by binchoo** [comment]
1장은 이렇게 요약되겠습니다.

1. 무상태 웹 계층
2. 모든 계층의 다중화 도입
3. 가능한 한계까지 캐시할 것 (CDN, 멤캐시)
4. 데이터 센터를 지원할 것
5. 정적 콘텐츠는 CDN이 서비스 할 것
6. 데이터 계층은 샤딩을 적용할 것, 읽기 연산을 분산할 것
7. 각 계층이 독립적으로 분할되어 느슨히 결합될 것 (레이어드 아키텍쳐, 비동기 메시지 큐)
8. 시스템을 지속적으로 모니터링하고 자동화 시킬 것
