### ISSUE TITLE
[question] 책에서 언급한 URL 단축기 해시 함수에 대해서 

### ISSUE THREAD

**Issue by ngwoon** [caffeine-library/system-design-interview#24]
## 질문

책에서 URL 단축기가 사용할 해시 함수는 아래 두 가지 요구사항을 만족해야 한다고 적혀 있습니다. (pg 131)
* 입력으로 주어지는 긴 URL이 다른 값이면 해시 값도 달라야 한다.
* 계산된 해시 값은 원래 입력으로 주어졌던 긴 URL로 복원될 수 있어야 한다.

첫 번째 요구사항은 이해가 가나, 두 번째 요구사항은 왜 필요한지 잘 이해가 안됩니다.
DB에 shorturl - longurl 쌍을 저장하기 때문에 shorturl을 longurl로 변환하는 작업이 딱히 필요없다는 생각이 들고 책에서도 그런 내용은 없는 듯 한데, 이에 대해 다들 어떻게 생각하시는지 궁금해서 질문남깁니다.

## 연관 챕터

#21 

@caffeine-library/readers-system-design-interview

**Comment by JasonYoo1995** [comment]
원래 URL로 복원한다는 2가지 의미로 해석될 수 있는데

1. Output(짧은 URL)를 통해 Input(원래 URL)을 구할 수 있는 해시 함수의 '역함수'를 통해 연산을 수행한다
2. GET의 과정 중에 DB를 통해 원래 URL를 얻어온다

말씀하신대로 1번은 불필요한 과정이므로, 2번을 의미하는 것이 아니었을까요?
책 번역의 과정에서 단어 선택이 부적절했을 수도 있고요

**Comment by JasonYoo1995** [comment]
<img width=300 src=https://user-images.githubusercontent.com/66045861/150662184-f0a67712-2024-4f75-8c53-7ebef134c975.png>

**Comment by binchoo** [comment]
영어 원문에 따르면 첫 째 조건은 must 조건이며, 둘 째는 can 조건인 것으로 확인되었습니다.

- 입력으로 주어지는 긴 URL이 다른 값이면 해시 값도 달라야 한다. (**must**)
- 계산된 해시 값은 원래 입력으로 주어졌던 긴 URL로 복원될 수 있어야 한다. (**can**)

두 번째 조건은 필수는 아니나, url 쇼트너의 특성에는 적합하여 소개된 것 같습니다. 왜냐하면 shortUrl에서 바로 longUrl을 얻어내므로 DB조회가 필요없기 때문입니다. 
![Screenshot_20220124-173132_Office](https://user-images.githubusercontent.com/15683098/150752896-dc76de33-11a6-4c21-92b1-998378ad564c.jpg)
