### ISSUE TITLE
[question] Load Balancer의 기능

### ISSUE THREAD

**Issue by JasonYoo1995** [caffeine-library/system-design-interview#9]
## 질문
로드밸런서의 기능과 종류, 알고리즘에 대해 더 조사해보기

## 연관 이슈
#8 

---

@caffeine-library/readers-system-design-interview

**Comment by binchoo** [comment]
AWS 로드밸런서 사양

## Application Load Balancer (L7)

## Network Load Balancer (L4)

## Gateway Load Balancer (L3)

## Classic Load Balancer (Deprecated)

**Comment by ngwoon** [comment]
OSI 7계층 중 어떤 계층에서 동작하는 로드밸런서인지에 따라 구분한다.

## L1

Physical Layer (1계층) 에서 동작하는 로드밸런서.

더미허브 라고 부른다.

데이터를 수신하면, 자신과 연결된 모든 노드에 broadcasting한다.

따라서 연결된 장치가 많을수록 대역폭이 떨어진다는 단점이 있다.

## L2

Data Link Layer (2계층) 에서 동작하는 로드밸런서.

L2 스위치 허브 혹은 스위치 라고 부른다.

ARP Request를 활용해 포트 - 연결된 노드의 MAC 주소 쌍을 저장하는 테이블을 갖고 있다.

따라서, 연결된 노드의 개수에 상관없이 각 연결에 대한 대역폭이 독립적이다.

## L3

Network Layer (3계층) 에서 동작하는 로드밸런서.

L3 스위치 혹은 라우터 라고 부른다. 

(엄밀히 말하면 쓰임새가 조금 다르지만, 너무 디테일한 내용인 것 같다. 이 글에서는 라우터 = L3 로드밸런서 라고 여기겠다. 자세한 내용은 [여기](https://community.fs.com/blog/layer-3-switch-vs-router-what-is-your-best-bet.html))

일반 가정집이 속한 LAN의 게이트웨이가 L3 로드밸런서이다.

L3 로드밸런서는 IP 주소 정보를 알 수 있기 때문에, 이를 활용한 트래픽 제어 & 라우팅 등이 가능하다.

## L4

Transport Layer (4계층) 에서 동작하는 로드밸런서.

도착지의 IP + 포트번호 정보까지 알 수 있기 때문에, 프로그램(프로세스) 단위의 부하 로드밸런싱이 가능하다.

L4부터는 하드웨어 뿐만 아니라 소프트웨어로 만들어지는 경우도 많다.

보통 L4 로드밸런서의 VIP로 클라이언트들이 접근하고, 각 요청에 따라 적절한 서버로 로드밸런싱한다.

## L7

Application, Presentation, Session Layer (7,6,5 계층) 에서 동작하는 로드밸런서.

데이터 페이로드까지 확인해 볼 수 있기 때문에, HTTP, FTP, SMTP 등의 프로토콜에 따른 로드밸런싱까지 가능하며, 데이터 악성코드 검사 등의 고급 기능 또한 가능하다. (네트워크 보안 분야에서 활용)

소프트웨어로 만들어지는 경우가 많다.

## 참고

L2 ~ L7

[https://nhj12311.tistory.com/75](https://nhj12311.tistory.com/75)

L4

[https://aws-hyoh.tistory.com/entry/L4-Switch-쉽게-이해하기](https://aws-hyoh.tistory.com/entry/L4-Switch-%EC%89%BD%EA%B2%8C-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0)

**Comment by JasonYoo1995** [comment]
<img src=https://user-images.githubusercontent.com/66045861/154839387-5035b0c5-1acc-4476-8a0b-e7b95359c839.png>
<img src=https://user-images.githubusercontent.com/66045861/154839399-23c0f9c5-1700-4df2-ba32-ef0a4341146c.png>
<img src=https://user-images.githubusercontent.com/66045861/154839405-281e8bb3-7a9c-458c-9ca1-19e214e10c66.png>

## 로드밸런서의 **종류**

- 로드밸런서는 L2, L3, L4, L7로 나눌 수 있다.
- L4 로드밸런서와 L7 로드밸런서가 가장 많이 활용된다.
    - L4 로드밸런서부터 포트(Port) 정보를 바탕으로 로드 분산이 가능하기 때문
    - 한 대의 컴퓨터에 다수의 서버 프로그램을 운영하는 경우라면,
    L4 이상의 로드밸런서를 사용해야 포트에 따라 스위칭할 수 있다.
- 상위 계층(숫자가 큰 계층)으로 갈수록 섬세한 부하 분산이 가능하지만 가격이 비싸진다
- 하위 계층(숫자가 작은 계층)으로 갈수록 간단한 부하 분산이 가능하고 가격이 저렴해진다.
- 상위 계층에서 사용되는 장비는 하위 계층의 장비가 갖고 있는 기능을 모두 가지고 있다.
- Li 스위치는 (i+1)~7번째 계층의 내용을 읽거나 쓸 수 없다.

### **L1 스위치 (허브, 더미 허브)**

- 물리 계층에서 작동한다.
- 자신에게 꽂혀있는 모든 장비에게 데이터를 전부 전달한다.

### **L2 로드밸런서 (L2 스위치)**

- 데이터 링크 계층을 기반으로 스위칭 가능
- MAC 주소를 바탕으로 Load Balancing한다

### **L3 로드밸런서 (L3 스위치)**

- 네트워크 계층을 기반으로 스위칭 가능
- IP주소나 IPX 주소를 바탕으로 Load Balancing한다

### **L4 로드밸런서 (L4 스위치)**

- 전송 계층를 기반으로 스위칭 가능
- 3계층의 IP주소와 더불어 TCP/UDP(=Port 번호) 정보까지도 보고 스위칭한다.
- 하나의 서버가 죽어 서비스가 중단되는 경우
    
    다른 서버로 해당 서비스를 대체하는 **ACTIVE-ACTIVE** / **ACTIVE-STANDBY** 기능도 한다.
    
- 7계층의 내용물을 보지 않기 때문에, TLS termination이 없다.

### **L7 로드밸런서 (L7 스위치)**

- 응용 계층을 기반으로 스위칭 가능
- 3계층의 IP주소, 4계층의 Port 정보와 더불어 5~7계층의 패킷 내용까지 모두 보고 스위칭한다
    - 7계층 내용의 예 : HTTP 헤더(Request URL, 쿠키 등), HTTPS, FTP, SMTP, WebSocket 등
- 패킷 내용까지 읽을 수 있기 때문에 제공되는 기능
    - 사용자의 요청 내용에 따라 스위칭 가능
    - 보안, 모니터링, 암호화, 인증, 웹 애플리케이션 방화벽, 바이러스 패턴 분석 등
    - Traffic filter, VPN, DDoS 방어 등
- L7 스위치를 **보안 스위치**라고 부르기도 한다.
- 7계층의 내용물을 보기 때문에, TLS termination이 일어난다.
<img src=https://user-images.githubusercontent.com/66045861/154839415-3f89875c-1abe-488f-8cc7-5201d5c79511.png>
<img src=https://user-images.githubusercontent.com/66045861/154839421-f911a13c-fdd9-4974-90f5-deb9e82c716f.png>
<img src=https://user-images.githubusercontent.com/66045861/154839423-8dad7b97-095a-41fa-a166-794186bb1d39.png>
<img src=https://user-images.githubusercontent.com/66045861/154839425-93367f5a-8a0a-41f0-97cb-92caa55bfa07.png>
<img src=https://user-images.githubusercontent.com/66045861/154839430-e6b4d270-981c-4d3a-a9ce-02d2c12e326b.png>

## **다양한 로드밸런싱 알고리즘**

- **라운드로빈 방식(Round Robin Method)**
    - 서버에 들어온 요청을 순서대로 돌아가며 배정
- **가중 라운드로빈 방식(Weighted Round Robin Method)**
    - 각각의 서버마다 가중치를 매기고 가중치가 높은 서버에 클라이언트 요청을 우선적으로 배분
- **IP 해시 방식(IP Hash Method)**
    - 클라이언트의 IP 주소를 해싱하여 특정 서버와 매핑
    - 사용자가 항상 동일한 서버로 연결되는 것을 보장
- **최소 연결 방식(Least Connection Method)**
    - 요청이 들어온 시점에 가장 적은 연결 상태를 보이는 서버에 우선적으로 트래픽을 배분
- **최소 리스폰타임(Least Response Time Method)**
    - 가장 적은 연결 상태와 가장 짧은 응답시간을 보이는 서버에 우선적으로 로드를 배분
